### ISSUE TITLE
error issue

### ISSUE THREAD

**Issue by akumas23** [Miltt/SMPPWindowsService#1]
hi,

I cannot send a message it says "error".. i already changed the cfg. is there any configuration i missed? Thank you

**Comment by Miltt** [comment]
Hello,

1. In what form do you use code - as the application or service? Any case, this code does not work "as is"
2. Make sure that you have correctly entered the settings SMPP. You can connect to smpp server from code? Check your SMPP settings, for example, [using this app](http://www.tops.com.pl/en/)
3. See [errors ](http://www.tops.com.pl/en/smscc/manual/error-codes/smpp.html)that can return server

**Comment by akumas23** [comment]
Hi Miltt,

Thanks for the response, here is the scenario i have a sms gateway device and i would like to connect it using your program is this possible?. I already change the cfg. ..I am using this as an application but there is an error that i need to install it as a service.  if this code does not work "as is" can you guide how this works. Thank you

**Comment by Miltt** [comment]
I think it will be easier to understand [native code Easy SMPP](https://sourceforge.net/projects/easysmpp/). The downloaded archive contains the source code and the application for the test.
